#
# debug use docker-compose.yml
#
version: '2'
services:
  pinrepo:
    build:
      context: .
    environment:
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "aws_secret_access_key"
      S3_BUCKET: "aaaa"
      S3_REGION: "ap-southeast-1"
    ports:
      - "8080:80"
    links:
      - localstack:s3-ap-southeast-1.amazonaws.com
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3:443
      - DEBUG=1
      - USE_SSL=true
    expose:
      - "80" # if USE_SSL=false and SERVICES=s3:80
      - "443"

